"""Pinned, import-rewritten copies of the production tracker's dependencies (see VENDORED.md). Generated by
scripts/vendor_tracker_v1.py — edit the generator or the pins, not these files, except for the marked
performance patches listed in VENDORED.md.
"""
