DEEPSORT_WORKER:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/scripted_ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.9
  MAX_IOU_DISTANCE: 0.6
  MAX_AGE: 100
  N_INIT: 6
  NN_BUDGET: 100
  METRIC_TYPE: "cosine"
  
DEEPSORT_TRANSPORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/scripted_ckpt.t7"
  MAX_DIST: 150
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.75
  MAX_AGE: 160
  N_INIT: 8
  NN_BUDGET: 100
  METRIC_TYPE: "euclidean"
