"""What uplink a station needs for real time, and what delay each chunk size and link speed gives.

The stream is a fact, not an estimate: every full-turn video of the test set is 1920x1080, 8 fps, H.264 at a constant
4.00 Mbit/s, and a station has two cameras. From that the delay of a result behind the camera is arithmetic:

    a chunk of T seconds has to be filmed          T
    then uploaded                                   T * (video bitrate of the station / uplink)
    then the worker goes through its frames         up to T * (frame path / 125 ms)

so the first frame of a chunk is the latest one (T + upload) and the last frame is the earliest (upload + processing of the
chunk). The model is checked against live runs of the branch over links of 4 to 12 Mbit/s (one camera, 30-frame chunks):
the runs are read from out/rt/runs/uplink_*/summary.json when they are on disk, otherwise from the stored JSON.

    python scripts/station_uplink.py
"""

from __future__ import annotations

import glob
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_MD = os.path.join(ROOT, "docs", "analysis", "station_requirements.md")
OUT_JSON = os.path.join(ROOT, "docs", "analysis", "station_requirements.json")

CAMERA_MBIT_S = 4.0  # measured: 21 full-turn videos, all exactly 4.00 Mbit/s (chunk peak 4.49)
CAMERAS = 2  # cone + wing
FPS = 8.0
FRAME_PATH_S = 0.060  # ten modules on a T4-class card with TensorRT heads: 60.2 ms (this machine: 44-56 ms)
RUN_FRAME_PATH_S = 0.045  # the frame path of the throttled-link runs themselves (one module, this machine)
CHUNK_FRAMES = (30, 60, 120, 480)
LINKS = (4, 8, 10, 15, 20, 30, 50, 100)


def delay(chunk_s: float, link: float, video: float, frame_path_s: float = FRAME_PATH_S) -> dict:
    upload = chunk_s * video / link
    behind = video > link
    return {"upload_s": round(upload, 1), "falls_behind": behind,
            "backlog_s_per_minute": round(60 * (video / link - 1), 0) if behind else 0,
            "delay_min_s": round(upload + chunk_s * frame_path_s * FPS, 1),
            "delay_max_s": round(chunk_s + upload + frame_path_s, 1)}


def measured_runs() -> list:
    rows = []
    for path in sorted(glob.glob(os.path.join(ROOT, "out", "rt", "runs", "uplink_*", "summary.json"))):
        s = json.load(io.open(path, encoding="utf-8"))
        if s.get("ingest") != "chunks" or not s.get("frame_latency_s"):
            continue
        rows.append({"link_mbit_s": s.get("bandwidth_mbps"), "keeps_up": s.get("keeps_up"),
                     "latency_s": s["frame_latency_s"],
                     "drift_s_per_recording_minute": s.get("latency_drift_s_per_recording_minute")})
    rows.sort(key=lambda r: r["link_mbit_s"])
    return rows


def band(d: dict) -> str:
    if d["falls_behind"]:
        return "falls behind"
    return f"{d['delay_min_s']:.0f}–{d['delay_max_s']:.0f} s"


def main() -> int:
    video = CAMERA_MBIT_S * CAMERAS
    runs = measured_runs()
    if not runs and os.path.exists(OUT_JSON):
        runs = json.load(io.open(OUT_JSON, encoding="utf-8")).get("measured_one_camera_30_frame_chunks", [])
    table = {str(n): {str(b): delay(n / FPS, b, video) for b in LINKS} for n in CHUNK_FRAMES}

    L = ["# What a station needs for real time: the uplink and the chunk", "",
         "Generated by `scripts/station_uplink.py`. Do not edit by hand.", "",
         "## In short", "",
         f"- One camera sends **{CAMERA_MBIT_S:.1f} Mbit/s** (1920x1080, 8 fps, H.264, constant bitrate: every one of the 21 "
         f"full-turn videos of the test set). A station has two cameras: **{video:.0f} Mbit/s, {video * 60 / 8:.0f} MB per "
         f"minute, {video * 3600 / 8 / 1000:.1f} GB per hour**.",
         f"- The uplink of the station has to be **above {video:.0f} Mbit/s**, or the station falls behind and never catches up.",
         "- A chunk has to be filmed before it can be sent, so **the chunk length sets the delay** and the link only decides "
         "how much is added on top: delay of the oldest frame = chunk length x (1 + 8 / uplink in Mbit/s).",
         "- With one-minute chunks a result is one to two minutes behind the camera whatever the link. For results within "
         "about ten seconds the chunk has to be 60 frames or less.",
         "- **20 Mbit/s of sustained upload per station** is the sensible target: the upload takes 40 % of the chunk time, "
         "which leaves room for retries. Above 50 Mbit/s nothing changes.", "",
         "## A chunk of one minute (what the cambox writes today)", "",
         "One minute from both cameras is 60 MB.", "",
         "| uplink of the station | to upload that minute | a result is behind the camera by | |",
         "|---|---|---|---|"]
    notes = {4: "half of the video: every minute of recording adds a minute of delay",
             8: "exactly the video: it holds, with no room for a single retry",
             10: "", 15: "", 20: "the target", 30: "", 50: "", 100: "the floor: the minute itself"}
    for b in LINKS:
        d = table["480"][str(b)]
        L.append(f"| {b} Mbit/s | {d['upload_s']:.0f} s | {'grows without limit' if d['falls_behind'] else band(d)} | {notes[b]} |")
    worst = {b: table["480"][str(b)]["delay_max_s"] for b in (10, 100)}
    L += ["", f"From 10 to 100 Mbit/s the worst delay only moves from {worst[10]:.0f} s to {worst[100]:.0f} s: the minute of "
          "filming is the floor.", "",
          "## Smaller chunks", "",
          "The same station (two cameras), the delay of a result behind the camera, earliest–latest frame of a chunk:", "",
          "| uplink | 30 frames (3.75 s) | 60 frames (7.5 s) | 120 frames (15 s) | 480 frames (1 min) |", "|---|---|---|---|---|"]
    for b in LINKS:
        L.append(f"| {b} Mbit/s | " + " | ".join(band(table[str(n)][str(b)]) for n in CHUNK_FRAMES) + " |")
    L += ["", "Chunk size per camera: " + ", ".join(f"{n} frames = {CAMERA_MBIT_S * n / FPS / 8:.1f} MB" for n in CHUNK_FRAMES)
          + ". A chunk cannot be shorter than one GOP (30 frames) without re-encoding.", "",
          "## What else the station needs", "",
          "- **Sustained upload, measured on site.** The number that matters is what the link really carries for hours, not "
          "the name of the tariff. A SIM link has to be measured at the gate before it is counted on.",
          f"- **Storage for an outage**: {video * 3600 / 8 / 1000:.1f} GB per hour of both cameras. The real-time worker skips "
          "the hole after a reconnect and does not catch up; the recording still goes to post-processing.",
          f"- **Traffic**: {video * 86400 / 8 / 1000:.0f} GB per station per day if the cameras never stop. It is the same "
          "video that is uploaded today, sent as it is filmed instead of after the event.",
          "- **No new hardware for results in minutes**: the cambox only records and sends, as now. A check that has to "
          "answer in seconds on the camera itself (hair policy, safety vests) needs an accelerator in the box; that has "
          "not been measured and is the hardware item of the roadmap.",
          "- **An address to send to**: outbound TCP to the ingest of the worker, later with a certificate per cambox "
          "(`ARCHITECTURE.md` of the realtime-pipeline repository).", "",
          "## How the numbers were obtained", "",
          "The bitrate is read from the files (`ffprobe`); chunk sizes from the chunker (576 chunks of one event: "
          "1.6–2.1 MB, median 1.83). The delay is the arithmetic of the module docstring, with the frame path of "
          f"{FRAME_PATH_S * 1000:.0f} ms measured for ten modules on a T4-class card with TensorRT heads."]
    if runs:
        L += ["", "The arithmetic against the branch run live over a throttled link (one camera, 30-frame chunks, 300 s of the "
              "busiest stretch):", "",
              "| link | measured, median | model, middle of a chunk | measured, 95th percentile | model, first frame of a chunk | "
              "measured, worst | keeps up |",
              "|---|---|---|---|---|---|---|"]
        for r in runs:
            b = r["link_mbit_s"]
            chunk_s = 30 / FPS
            upload = chunk_s * CAMERA_MBIT_S / b
            mid = chunk_s + upload + 15.5 * RUN_FRAME_PATH_S - 14.5 / FPS
            L.append(f"| {b:g} Mbit/s | {r['latency_s']['p50']:.1f} s | {mid:.1f} s | {r['latency_s']['p95']:.1f} s | "
                     f"{chunk_s + upload + RUN_FRAME_PATH_S:.1f} s | {r['latency_s']['max']:.1f} s | "
                     f"{'yes' if r['keeps_up'] else 'no'} |")
        L += ["", "The worst frames belong to the largest chunks (up to 12 % above the median size). At 4 Mbit/s the single "
              "camera is exactly at its own bitrate: it holds (the delay does not grow), with nothing to spare."]
    io.open(OUT_MD, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    json.dump({"camera_mbit_s": CAMERA_MBIT_S, "cameras_per_station": CAMERAS, "frame_path_s": FRAME_PATH_S,
               "station_delay_by_chunk_frames_and_link": table, "measured_one_camera_30_frame_chunks": runs},
              io.open(OUT_JSON, "w", encoding="utf-8", newline="\n"), indent=1)
    for b in LINKS:
        print(f"{b:4d} Mbit/s | " + " | ".join(f"{n}f: {band(table[str(n)][str(b)])}" for n in CHUNK_FRAMES))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
